//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionsOfItems
    {
        public int Id { get; set; }
        public int ApartmentId { get; set; }
        public int ConditionType { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public string Status { get; set; }
    
        public virtual Apartments Apartment { get; set; }
        public virtual ConditionTypes ConditionType1 { get; set; }
    }
}
