//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OestbanehusModel : DbContext
    {
        public OestbanehusModel()
            : base("name=OestbanehusModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartments> Apartments1 { get; set; }
        public virtual DbSet<Buildings> Buildings1 { get; set; }
        public virtual DbSet<Cities> Cities1 { get; set; }
        public virtual DbSet<Comments> Comments1 { get; set; }
        public virtual DbSet<ConditionsOfItems> ConditionsOfItems1 { get; set; }
        public virtual DbSet<ConditionTypes> ConditionTypes1 { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Requests> Requests1 { get; set; }
    }
}
